spring:
  application:
    name: oauth2-client
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liuwkbMcIyj77QYo
            client-secret: 93e830a462e159be398a7282a7e4c0b590f89cc2

server:
  port: 8090