spring:
  application:
    name: crud_demo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/interview-test?useUnicode=true&characterEncoding=UTF-8
    hikari:
      minimum-idle: 5 #???????
      maximum-pool-size: 20 #?????
      idle-timeout: 30000 #??????????
      connection-timeout: 30000 #????????
      max-lifetime: 600000 #????????
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
