spring:
  application:
    name: spring-security-demo
  security:
    user:
      name: admin
      password: 123
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: sys
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver
#
#mybatis-plus:
#  mapper-locations: classpath*:mapper/**/*.xml # Mapper XML文件的位置
#  global-config:
#    db-config:
#      id-type: auto # 主键生成策略，这里设置为自动增长
#      logic-delete-value: 1 # 逻辑删除标记为已删除的值
#      logic-not-delete-value: 0 # 逻辑删除标记为未删除的值
#  configuration:
#    map-underscore-to-camel-case: true # 开启驼峰命名法映射
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 打印SQL日志到控制台

mybatis-plus:
  configuration:
    #开启驼峰命名自动映射
    map-underscore-to-camel-case: true
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #扫描mapper文件
  mapper-locations: classpath:mapper/**/*.xml

server:
  servlet:
    context-path: /demo

logging:
  level:
    org:
      springframework: DEBUG
    com:
      baomidou:
        mybatisplus: DEBUG