spring:
  application:
    name: spring-security-demo
  security:
    user:
      name: admin
      password: 123
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity-learn?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  configuration:
    #开启驼峰命名自动映射
#    map-underscore-to-camel-case: true
    #开启日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  #扫描mapper文件
  mapper-locations: classpath:mapper/**/*.xml

server:
  port: 8082
#  servlet:
#    context-path: /demo

springdoc:
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 的访问路径
    enabled: true # 是否启用 Swagger UI
  api-docs:
    path: /v3/api-docs # OpenAPI 文档的访问路径
    enabled: true # 是否启用 OpenAPI 文档
  default-produces-media-type: application/json # 默认的响应类型
  default-consumes-media-type: application/json # 默认的请求类型

#logging:
#  level:
#    org:
#      springframework: DEBUG
#    com:
#      baomidou:
#        mybatisplus: DEBUG